### ISSUE TITLE
How to define customized output format?

### ISSUE THREAD

**Issue by xxllgg** [glarue/palign#1]
Hi there,

Thank you for providing this excellent tool that accelerates the blast process!

I want to change the default output format to a customized output format: "-outfmt '6 qseqid qlen sseqid slen frames pident nident length mismatch gapopen qstart qend sstart send evalue bitscore'".
And I changed the code in palign (line 547): OUT_FORMAT = '\"6 qseqid qlen sseqid slen frames pident nident length mismatch gapopen qstart qend sstart send evalue bitscore\"'#args.out_fmt, 
but I couldn't get the right format. 
The log content is: 
[#]BLAST:'/media/psdz/data5/rosa_genome/phylogenomics/1.gene_family/compare1/mrna_all/1.find_orthologs/a18.cds.fa.0.99.modi.768951.02.chunk' vs. '/media/psdz/data5/rosa_genome/phylogenomics/1.gene_family/com>
[#] Starting BLAST run '/media/psdz/data5/rosa_genome/phylogenomics/1.gene_family/compare1/mrna_all/1.find_orthologs/a18.cds.fa.0.99.modi.768951.03.chunk' vs. '/media/psdz/data5/rosa_genome/phylogenomics/1.gen>
blastn -db /media/psdz/data5/rosa_genome/phylogenomics/1.gene_family/compare1/mrna_all/1.find_orthologs/a18.cds.fa.0.99.modi -query /media/psdz/data5/rosa_genome/phylogenomics/1.gene_family/compare1/mrna_all/1>
BLAST query/options error: '"6' is not a valid output format
Please refer to the BLAST+ user manual.  
Could you please give me some advice? Thanks!

Xiaolong

**Comment by glarue** [comment]
Hi Xiaolong,

Sorry for the trouble—this appears to be an annoying edge case where the `-outfmt` argument to BLAST is being consumed by Python's `parse_known_args()` function (which is used to separate out arguments destined for `palign` and those to be sent along to the selected aligner).

I had thought I'd solved this problem a long time ago but I couldn't get anything to work on my end, so the solution is to change the `-o` argument to `palign` to `-n` instead (so that Python doesn't interpret the `-o` part of `-outfmt` as the `--output_name` argument to `palign`. 

I've made that change in aa1b30203bfd3f2180bc8f9b733273488fd46138, but you could also modify your own script locally (line 489).

To run, you would include the `-outfmt` flag as a normal command-line argument to `palign`, followed by your BLAST format string in quotes, e.g. `palign <query> <target> <blast> -outfmt '6 qseqid qlen sseqid slen frames pident nident length mismatch gapopen qstart qend sstart send evalue bitscore'`

Hope that all makes sense; let me know if anything still doesn't work as expected!
